name: Hello World Workflow
on:
  pull_request:  # Triggers on every PR (opened, updated, reopened) testing12
    #types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Get PR Number and Branch Name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Triggered by a Pull Request"
            echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
            echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            echo "Triggered manually or by push"
            echo "PR_NUMBER=none" >> $GITHUB_ENV
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
            
      - name: Show Extracted Details
        run: |
          echo "Pull Request Number: $PR_NUMBER"
          echo "Source Branch Name: $BRANCH_NAME"
          
      - name: Make API Call Using PR Number
        run: |
          curl -X GET "https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json"
